name: app_location
description: A Flutter project

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.2
  font_awesome_flutter: ^10.5.0
  location: ^5.0.0
  http: ^1.4.0
  shared_preferences: ^2.0.15
  dio: ^5.4.0
  flutter_secure_storage: ^8.0.0
  latlong2: ^0.9.0 
  flutter_map: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

Variable name:  JAVA_HOME
Variable value: C:\Program Files\Eclipse Adoptium\jdk-21.0.7.6-hotspot
